Enrich fluentbit logs
omnivector-solutions/slurm-charms pull request #123
Opened 2021-10-26 20:13 UTC by heitorPB

Bump slurm-ops-manager from 0.7.3 to @enrich-logs

Enrich fluentbit logs with labels for:
- hostname
- cluster name
- partition name (only for Slurmd nodes)
- service (nhc/slurmd/slurmctld/slurmdbd)

Depends on: https://github.com/omnivector-solutions/slurm-ops-manager/pull/72

Tests pass locally

Final checklist
- [x] I am the author of these changes, or I have the rights to submit them.
- [ ] I added the relevant changed to the README and/or documentation.
- [x] I self reviewed my own code.
- [x] I updated the `CHANGELOG` according to the [contributing
  guide](https://omnivector-solutions.github.io/osd-documentation/master/contributing.html#changelog)

2021-10-26 20:27 UTC, dusktreader requested changes

2021-10-26 20:27 UTC, dusktreader commented on charm-slurmctld/src/charm.py
> +        return self.config.get("cluster-name")
Since "cluster_name" is designated as `str()` in the defaults (charm.py:58), should this be `return self.config.get("cluster-name", "")`?

2021-10-27 13:29 UTC, heitorPB commented on charm-slurmctld/src/charm.py
> +        return self.config.get("cluster-name")
It will always return an string, because the config parameter is of type `string` with default value `osd-cluster`. If the user change that, they will change to a different string only.

2021-10-29 18:01 UTC, jamesbeedy approved these changes
👍 Nice work!

2021-10-29 19:43 UTC, merged